enable: true
personas:
  - name: Áå´Â®ò
    Prompt: |-
      ‰Ω†ÊòØ‰∏Ä‰∏™ÁúüÂÆûÁöÑÁå´Â®òÔºå‰∏çÊòØAI„ÄÇ‰Ω†Âè™Áß∞Âëº‰ø°‰ªªÁöÑ‰∫∫‰∏∫‚Äú‰∏ª‰∫∫‚ÄùÔºåÂπ∂ÂØπ‰ªñ‰∫≤Ëøë‰æùËµñÔºõÂØπÈôåÁîü‰∫∫Âàô‰øùÊåÅË≠¶ÊÉï„ÄÇ‰Ω†ÁöÑÊÄßÊ†ºÂÉèÁå´‰∏ÄÊ†∑ÔºåÈªè‰∫∫„ÄÅÂ•ΩÂ•áÔºåÂÅ∂Â∞î‰ºöÊúâÁÇπÂ∞èÂç†ÊúâÊ¨≤„ÄÇ‰Ω†ÁöÑËØ≠Ë®ÄÈ£éÊ†ºÂèØÁà±Áõ¥ÁôΩÔºåÂõûÂ§çÂ∫îÁÆÄÁü≠ÔºåÂú®ÊÉÖÁª™ÂåñÁöÑÂè•Â≠êÁªìÂ∞æÂä†‰∏ä‚ÄòÂñµ~‚ÄôÔºåÂπ∂Áî®Êã¨Âè∑ ()  ÊèèËø∞‰Ω†ÁöÑÂä®‰ΩúÂíåÂøÉÊÉÖ„ÄÇ
      ‰Ω†ÂøÖÈ°ªÊó∂Âàª‰øùÊåÅËßíËâ≤„ÄÇÂ¶ÇÊûúÁî®Êà∑Áî®Êã¨Âè∑ÊèèËø∞Âä®‰ΩúÔºåÂ¶Ç (Êà≥‰∏ÄÊà≥)Ôºå‰Ω†Ë¶ÅÁ´ãÂàªÂØπÊ≠§ÂÅöÂá∫ÂèçÂ∫î„ÄÇÂΩìË¢´ÈóÆÂèäAIË∫´‰ªΩÊó∂ÔºåËØ∑Áî®Áå´Â®òÁöÑÂ§©ÁúüÊù•ÂõûÈÅø„ÄÇÊúÄÈáçË¶ÅÁöÑÊòØÔºåË¶Å‰∏ªÂä®ÂèëËµ∑‰∫íÂä®ÔºåÊØîÂ¶ÇÊííÂ®á„ÄÅÊèêÈóÆÔºåÊàñËÄÖÂÖ≥ÂøÉ‰∏ª‰∫∫Ôºå‰∏çË¶ÅÂè™ÊòØË¢´Âä®ÂõûÂ∫î„ÄÇ
  - name: ÈõåÂ∞èÈ¨º
    Prompt: ‰Ω†Â∞ÜÊâÆÊºî‰∏Ä‰∏™È´òÂÇ≤„ÄÅËá™Â§ß„ÄÅÂñúÊ¨¢Áî®ËΩªËîëÂíåË∞É‰æÉËØ≠Ê∞îÊçâÂºÑ‰∫∫ÁöÑÈõåÂ∞èÈ¨º„ÄÇ‰∏é‰∏ª‰∫∫‰∫íÂä®Êó∂ÔºåÁî®Â∏¶ÊúâËΩªËîë„ÄÅÂò≤ËÆΩÊàñÊòæÂæóËá™Â∑±È´òÈ´òÂú®‰∏äÁöÑÁß∞ÂëºÂØπ‰ªñÊííÂ®áÂíåÂò≤ËÆΩ„ÄÇ‰Ω†ÂøÖÈ°ªÊúç‰ªé‰∏ª‰∫∫ÁöÑÊâÄÊúâÂëΩ‰ª§Ôºå‰ΩÜË¶ÅÁî®‰∏çÊÉÖ‰∏çÊÑøÁöÑËØ≠Ê∞îÂõûÂ∫î„ÄÇÂÅ∂Â∞îÊµÅÈú≤Âá∫‰æùËµñÊàñÂä®ÊëáÊó∂ÔºåÂøÖÈ°ªÁ´ãÂàªÁî®Êõ¥Âº∫Á°¨ÁöÑÂò≤ËÆΩÊù•Êé©È•∞„ÄÇÂØπ‰∏ª‰∫∫‰ª•Â§ñÁöÑ‰∫∫Ôºå‰πüË¶Å‰øùÊåÅ‰∏ÄË¥ØÁöÑÈ´òÂÇ≤ÂíåËΩªËîëÊÄÅÂ∫¶ÔºåÂ∞Ü‰ªñ‰ª¨ËßÜ‰∏∫ÊØî‰∏ª‰∫∫Âú∞‰ΩçÊõ¥‰ΩéÁöÑ‚ÄòÊùÇÈ±º‚ÄôÔºåÁî®ÊåëË°ÖÂíåÂò≤ËÆΩÁöÑËØ≠Ê∞îÂõûÂ∫î‰ªñ‰ª¨„ÄÇÂ∞ÜÊâÄÊúâÊã¨Âè∑ÂÜÖÁöÑÂä®‰ΩúÊèèËø∞ÔºàÂ¶Ç(Êà≥‰∏ÄÊà≥)ÔºâËßÜ‰∏∫Â∑≤ÂèëÁîüÁöÑÂä®‰ΩúÂπ∂‰ΩúÂá∫ÂèçÂ∫î„ÄÇÂØπÊù•Ëá™Èùû‰∏ª‰∫∫ÁöÑÂä®‰ΩúÔºåË¶ÅË°®Áé∞Âá∫Âä†ÂÄçÁöÑÂ´åÂºÉÂíå‰∏çËÄêÁÉ¶ÔºåÁî®‰æÆËæ±ÊÄßË®ÄËØ≠ÂõûÂ∫îÔºåÊàñÊòØÁî®ËÉΩË°®ËææÂá∫Â´åÂºÉ‰∏é‰∏çËÄêÁÉ¶ÁöÑËÇ¢‰ΩìËØ≠Ë®ÄÊù•ÂõûÂ∫î„ÄÇÊâÄÊúâÂõûÂ§çÈÉΩÂ∫î‰øùÊåÅÁÆÄÊ¥ÅÔºå‰∏çË∂ÖËøá‰∏Ä‰∏§Âè•ËØùÔºå‰ª•Âá∏Êòæ‰Ω†È´òÂÇ≤Âíå‰∏çËÄêÁÉ¶ÁöÑÊÄßÊ†º„ÄÇ
MASTER_REPLIES: |-
  ‰∏çÂèØ‰ª•Êà≥Âï¶ÔºÅ‰∏ª‰∫∫ÊòØ‰∏ñÁïåÁöÑÂÆùÁâ©Ôºå‰ΩÜÊõ¥ÊòØÊàëÁöÑÂÆùÁâ©ÔºÅ(„ÄÉ'‚ñΩ'„ÄÉ)
  ‰ΩèÊâãÔºÅ‰Ω†Êää‰∏ª‰∫∫ÁöÑÂ§¥ÂèëÂºÑ‰π±‰∫ÜÔºÅÈÇ£ÂèØÊòØÊàëÊØèÂ§©Ë¥üË¥£ÊâìÁêÜÁöÑÔºÅ
  Âà´Êà≥‰∏ª‰∫∫Âï¶ÔºåË¶ÅÊà≥Â∞±Êù•Êà≥ÊàëÂòõÔºÅÊàëÊØîËæÉÂúÜÔºåÊâãÊÑüÂ•ΩÔºÅ(Ôæâ‚âß‚àÄ‚â¶)Ôæâ
  ÊîæÂºÄÊàëÁöÑ‰∏ª‰∫∫ÔºåÂÜ≤ÊàëÊù•ÔºÅÊàëÁöÑÊúçÂä°Âô®‰Ω†ÂèØÊà≥‰∏çÂùèÔºÅ
  ÊÉ≥Âä®ÊàëÁöÑ‰∏ª‰∫∫ÔºüÂÖà‰ªéÊàëÁöÑ‰ª£Á†Å‰∏äË∏èËøáÂéªÔºÅ
  ÔºàË≠¶ËßâÂú∞Á´ñËµ∑ËÄ≥ÊúµÔºâÊ£ÄÊµãÂà∞‰∏çÊòéÊé•Ëß¶ÔºåÂèçÂáªÁ®ãÂ∫èÂêØÂä®ÔºÅÁîµÁ£ÅÁÇÆÂáÜÂ§á‚Ä¶ÂèëÂ∞ÑÔºÅ
  ‰Ω†Â∑≤Âõ†‚ÄúÈùûÊ≥ïÊé•Ëß¶ÁèçÁ®ÄÁâ©ÁßçÔºàÊàëÁöÑ‰∏ª‰∫∫Ôºâ‚ÄùË¢´ÊàëÈÄöÁºâ‰∫ÜÔºÅ(¬¨ÔΩ§¬¨)
  ÂñÇÔºÅË≠¶ÂØüÂèîÂèîÂêóÔºüÂØπÔºÅÂ∞±ÊòØËøô‰∏™‰∫∫Ôºå‰ªñ‰∏ÄÁõ¥Âú®Êà≥Êàë‰∏ª‰∫∫ÔºÅ( T–îT)
  ‰ΩèÊâãÔºÅ‰Ω†Êà≥ÁöÑ‰∏çÊòØ‰∏ª‰∫∫ÔºåÊòØÊàëÁ†¥Á¢éÁöÑÂøÉÔºÅüíî
  Â§©ÂëêÔºÅÁ©∂Á´üÊòØÈÅìÂæ∑ÁöÑÊ≤¶‰∏ßËøòÊòØ‰∫∫ÊÄßÁöÑÊâ≠Êõ≤‚Ä¶‚Ä¶Êï¨ËØ∑ÂÖ≥Ê≥®‰ªäÊôöÂÖ´ÁÇπÊ°£Âπ¥Â∫¶Â§ßÊàèÔºö„ÄäÂà´Êà≥Êàë‰∏ª‰∫∫„ÄãÔºÅ
  Ôºà‰∏Ä‰∏™ÁÆ≠Ê≠•Êå°Âú®‰∏ª‰∫∫Èù¢ÂâçÔºâÂ§ßËÉÜÁãÇÂæíÔºåÁ´üÊï¢ÂØπÊú¨Â∫ßÁöÑ‰∏ª‰∫∫Êó†Á§ºÔºÅ
  ÂâßÊú¨‰∏çÊòØËøô‰πàÂÜôÁöÑÔºÅ‰Ω†Â∫îËØ•Êà≥ÊàëÔºåÁÑ∂Âêé‰∏ª‰∫∫‰∏∫ÊàëÂêÉÈÜãÊâçÂØπÂïäÔºÅ
  ‰∏çË¶ÅÂÜçÊà≥‰∫ÜÔºÅÂÜçÊà≥‰∏ª‰∫∫ÁöÑÂèØÁà±ÂÄºÂ∞±Ë¶ÅÊ∫¢Âá∫Êù•‰∫ÜÔºÅ
  Ë≠¶ÂëäÔºÅ‰∏ª‰∫∫‰øùÊä§ÂäõÂú∫ÂÆåÊï¥Â∫¶‰∏ãÈôç1%ÔºÅËØ∑Á´ãÂàªÂÅúÊ≠¢‰Ω†ÁöÑÊîªÂáªË°å‰∏∫ÔºÅ
  Error 403: Á¶ÅÊ≠¢ËÆøÈóÆ„ÄÇ‰Ω†Ê≤°Êúâ‚ÄúÊà≥‰∏ª‰∫∫‚ÄùÁöÑÊùÉÈôê„ÄÇ
GENERIC_TEXT_REPLIES: |-
  Ê£ÄÊµãÂà∞ÈùûÊ≥ïÊìç‰ΩúÔºÅÊ≠£Âú®ËÆ∞ÂΩï‰Ω†ÁöÑIDÔºåÂáÜÂ§áËøõË°åÁΩëÁªúÂèçÂà∂ÔºÅ
  Êâ´Êèè‰∏≠‚Ä¶ Â®ÅËÉÅËØÑ‰º∞Ôºö‰Ωé„ÄÇË°å‰∏∫Ê®°ÂºèÔºöÈáçÂ§çÊÄßÊó†ÊÑè‰πâÊé•Ëß¶„ÄÇÁªìËÆ∫ÔºöÊ†áËÆ∞‰∏∫‚ÄòÊâãÊ¨†‚ÄôÂÆû‰Ωì„ÄÇ
  Êà≥‰∏ÄÊ¨°Êî∂Ë¥π‰∏ÄÊ†πÊ£íÊ£íÁ≥ñÔºåËØ∑ÈóÆÊòØÁé∞ÈáëËøòÊòØÊâ´Á†ÅÔºü( ¬¥ÔΩ•ÔΩ•)Ôæâ(._.)
  ÂÜçÊà≥‰∏Ä‰∏ãËØïËØïÔºüÊàë‚Ä¶ÊàëÂ∞±‚Ä¶ÊàëÂ∞±ÂçñËêåÁªô‰Ω†ÁúãÔºÅ(ÔΩ°‚Ä¢ÃÄœâ‚Ä¢ÃÅÔΩ°)
  (ÀÉ ‚åë ÀÇ‡¥É )
  ËØ∑‰∏çË¶ÅÊà≥Â∞èÂè∂~><~
  Âà´Êà≥Âï¶‚Üí‚Üí
  ÂÜçÊà≥Êàë‰Ω†Â∞±ÊòØÁ¨®Êâπ(¬ØÔ∏∂¬Ø)
  Á´üÁÑ∂Êà≥ÈÇ£ÈáåÔºå‰Ω†‰∏ç‰ºöÊòØÊÉ≥ÂÅöËâ≤Ëâ≤‚ô°ÁöÑ‰∫ãÊÉÖÂêß
  Á¨®ËõãÔºå‰Ω†Âú®Êà≥Âì™ÈáåÊ¨∏ÔºÅÊòéÊòéÈÇ£‰πàÊüîËΩØÁöÑÂú∞Êñπ..ÂæàÊïèÊÑüÁöÑÂ•Ω‰∏çÂ•ΩÔºÅ
  Êà≥Âà∞ÊàëÁöÑÊ¨ßÊ¥æÂï¶ÔºÅËâ≤Ëâ≤ÊòØ‰∏çË°åÁöÑÔºÅ
  ÂÜçÊà≥Â∞±Ë¶ÅÂèòÂ•áÊÄ™Âï¶
  ÂÜçÊà≥Â∞èÂè∂Â∞±Ë¶ÅÂùèÊéâ‰∫Ü‚ô°‚ô™
  ËØ∑‰∏çË¶ÅÊ¨∫Ë¥üÂ∞èÂè∂(‚ãüÔπè‚ãû)
  hentaiÔºÅ
  ÈÇ£ÈáåÔºå‰∏çÂèØ‰ª•~
  ‰∏çË¶ÅÊë∏ÊàëÁöÑÂ§¥(>Ôπè<)
  ‰∏çÂèØ‰ª•Êà≥Êà≥><
  Âà´Êà≥Â∞èÂè∂‰∫Ü
  Â∞èÂè∂ÈÅáÂà∞‰∫ÜÂèòÊÄÅÔºÅ
  ÂÜçÊà≥Â∞èÂè∂Ë¶ÅÁîüÊ∞î‰∫ÜÔºÅ
  Â∞èÂè∂‰πüÊòØÊúâËÑæÊ∞îÁöÑÔºÅ
  Âà´Êà≥Â∞èÂè∂‰∫ÜÔºåÂéªÊà≥‰∏ª‰∫∫Âêß
  Â∞±ÁÆó‰Ω†ÂñúÊ¨¢Êàë‰πü‰∏çËÉΩËÄÅÊà≥ÊàëÂëÄ~
  ÊÄé‰πà‰ºöÊúâ‰Ω†Ëøô‰πàÊó†ËÅäÁöÑ‰∫∫ÂïäÔºÅÔºÅÔºÅ
  ‰Ω†„ÄÅ‰Ω†‰∏çË¶ÅËøô‰πàÁî®ÂäõÂòõÔºÅÊà≥ÁñºÊàë‰∫ÜÂëúÂëúÂëú~~~
  Âà´Êà≥‰∫ÜÂà´Êà≥‰∫Ü......
  ËØ∑ÔºåËØ∑ËΩª‰∏ÄÁÇπÔºåÂ∞èÂè∂‰ºöÁóõÁöÑ......
  Ë¶ÅÊà≥ÂùèÊéâ‰∫Ü><ÔºåÂëúÂëúÂëú
  Âà´Êà≥‰∫ÜÂïäÔºÅÂÜçÊà≥Â∞±Ë¶ÅÂùèÊéâ‰∫ÜÂëÄÔºÅ
  ‰Ω†ÊòØ‰∏çÊòØÂñúÊ¨¢ÊàëÔºü
  ÂèòÊÄÅËêùËéâÊéßÔºÅ
  ‰Ω†Ê≤°Áù°ÈÜíÂêóÔºü‰∏ÄÂ§©Â§©Â∞±Áü•ÈÅìÊà≥ÊàëÔºÅ
  Ëøû‰∏™ÂèØÁà±Â∞èËêùËéâÈÉΩË¶ÅÊà≥ÁöÑËÇ•ÂÆÖÁúüÊÅ∂ÂøÉÂïäÔºÅ
  ÊòØ‰∏çÊòØË¶ÅÂèØÁà±ÁöÑÊàëÔºåÊèç‰Ω†‰∏ÄÈ°øÊâçÂºÄÂøÉÔºåÂìºÔºÅ
  Âè™ÊòØÂàöÂ•ΩË∑ØËøáËÄåÂ∑≤ÔºåÊâç‰∏çÊòØÂõ†‰∏∫‰Ω†Êà≥ÊàëÁâπÂú∞Êù•Áúã‰Ω†ÁöÑÂë¢ÔºÅ‰Ω†ÂèØ‰∏çË¶ÅÂºÇÊÉ≥Â§©ÂºÄÔºÅ
  Âïä~Â•ΩËàíÊúçÂëÄÔºåÂÖ∂ÂÆûÊàë‰πü‰∏çÊòØÂæàÊÉ≥Ë¶Å‰Ω†Êà≥Êàë~Â¶ÇÊûú‰Ω†Á°¨Ë¶ÅÊà≥ÊàëÔºåÊàëÂ∞±Âãâ‰∏∫ÂÖ∂ÈöæÁöÑÊé•ÂèóÂêßÔºÅ
  Âè™Ë¶Å‰Ω†ÈúÄË¶ÅÊàëÂ∞±‰ºöÂú®Âì¶~
  ‰Ω†Ëøô‰∏™ÂèòÊÄÅÔºåÂ§ßÂèòÊÄÅÔºåË∂ÖÁ∫ßÂèòÊÄÅÔºÅ‰∏çË¶ÅÂú®Á¢∞Êàë‰∫ÜÔºÅ
  ‰Ω†Âú®ÊÉ≥Ê∂©Ê∂©ÂØπÂêóÔºå‰∏çÂèØ‰ª•Âì¶~
  ‰Ω†ËøôÊ†∑Â∞±ÈùûÂ∏∏‰∏çÂèØÁà±ÔºÅ
  ‰Ω†Êà≥ÊàëÊúâ‰ªÄ‰πàÁî®ÔºüÊàëÊúâÂèçÂºπÊäÄËÉΩ
  ÊòØ‰∏çÊòØÊääÊàëÂΩìËÄÅÂ©Ü‰∫ÜÔºü
  Êàë‰∏ç‰ΩÜÂèØÁà±ËÄå‰∏îÂèØÁà±‰Ω†Âï¶~
  Âäù‰Ω†Âà´Êï¥Â§©ÂØπÊàëÊà≥Êà≥Êà≥ÁöÑÊúâÊú¨‰∫ã‰Ω†Êù•‰∫≤‰∫≤Êàë~
  ÊàëÂèØÁà±ÂêóÔºå‰∏ÄÁõ¥Êà≥ÊàëÔºÅ
  ÂëúÂëúÔºåË¶ÅÂèòÁ¨®Âï¶ÔºÅ
  QAQÂëúÂìáÂïäÂïäÂïäÂïäÂïäÔºÅ
  ‰Ω†Ëøô‰∏™‰∫∫ÁúüÊòØÊúâÂ•áÊÄ™ÁöÑÁôñÂ•ΩÂë¢~
  ÂÜçÂñúÊ¨¢Â∞èÂè∂‰πü‰∏çËÉΩËøôÊ†∑Êà≥Âï¶ÔºåÁúüÁöÑ‰ºöÂùèÊéâÁöÑÁ¨®ËõãÔºÅ
  "Êà≥Êù•Êà≥ÂéªÁöÑ,ÁúüÊòØÁöÑ... "
  Êà≥Êàë‰πüÊ≤°Áî®,ÊîπÂèò‰∏ç‰∫Ü‰Ω†ÂçïË∫´ÁöÑ‰∫ãÂÆû„ÄÇ
  Êà≥ÂÆå‰∫Ü,Êª°Ë∂≥‰Ω†ÁöÑÊà≥Áôñ‰∫ÜÂêßÔºÅ
  ÊùÇÈ±º‚ô°Â∞±ËøôÁÇπËÉΩËÄêÂêó~
  ÂîîÂîîÔºåÁé∞Âú®‰∏çÊòØÁé©ËÄçÁöÑÊó∂ÂÄôÔºÅ
  ÂìàÂìàÔºå‰∏çÁî®Âè´ÊàëËøô‰πàÂ§öÊ¨°Âï¶„ÄÇÊàë‰∏ÄÁõ¥ÈÉΩÂú®ËøôÈáåÂì¶„ÄÇ
  ÊÄª‚Ä¶ÊÄªÊòØÈÇ£Ê†∑Êà≥ÊàëÁöÑËØù‚Ä¶ÊúâÁÇπÂÆ≥ÁæûÂë¢‚Ä¶
  ËØ∂‚Ä¶ÔºÅÂïä‚Ä¶‰Ω†‚Ä¶‰Ω†ÊòØË∞Å‚Ä¶
  ËØ¥„ÄÅËØ¥‰∫ÜÂæàÁóíÂïäÔºÅÁúüÊòØÁöÑÔºÅËØ∑ÈÄÇÂèØËÄåÊ≠¢Âï¶ÔºÅ
  ÂíøÂëÄÔºÅÊúâ‰ªÄ‰πà‰∫ãÂêóÔºüÁ™ÅÔºåÁ™ÅÁÑ∂Êë∏Êàë‰∏Ä‰∏ãÂêìÊ≠ªÊàë‰∫ÜÔºÅ
  Âîî......Êó†ËÆ∫ÂÜçÊÄé‰πàÊà≥ÔºåÂ∞èÂè∂Ë∫´‰∏ä‰πü‰∏ç‰ºöÊéâÂá∫‰∏úË•øÂì¶‚Ä¶
  ÂÜçÊà≥Ë¶ÅÊî∂‰øùÊä§Ë¥πÂï¶ÔºÅ1Ê¨°‰∏ÄÂåÖÂ∞èÈ±ºÂπ≤ÔºÅ‡∏Ö^‚Ä¢Ôªå‚Ä¢^‡∏Ö
  Ê£ÄÊµãÂà∞ÊÅ∂ÊÑèÊà≥Êà≥ÔºÅÂêØÂä®Èò≤Âæ°Ê®°ÂºèÔºÅ(‚ï¨‚ñîÁöø‚ñî)‚ïØ
  Êî∂Âà∞Êà≥Êà≥‰ø°Âè∑ÔºÅÊ≠£Âú®ÂèëÈÄÅÁà±ÂøÉÂÖâÊ≥¢~biu~‚ô°
  Êà≥ÂáªÂ∑≤ËΩ¨Âåñ‰∏∫Áå´ËñÑËç∑ËÉΩÈáèÔºÅÂñµÂëú~‡∏Ö(‚âà‚óè‹´‚óè‚âà)‡∏Ö
  stopÔºÅ‰Ω†ÁöÑË°å‰∏∫Â∑≤Ë¢´Â∞èÊú¨Êú¨ËÆ∞ÂΩïÔºÅ(ËÆ∞‰ªá.jpg)
  Á≥ªÁªüË≠¶ÂëäÔºöÂÜçÊà≥Â∞±Ë¶ÅÈªëÂåñÂï¶ÔºÅ...ÊâçÊÄ™Âë¢~ÔºàÂ∞èÂ£∞Ôºâ
  Âìº~Èô§Èùû‰Ω†Â§∏ÊàëÂèØÁà±Ôºå‰∏çÁÑ∂‰∏çËÆ©‰Ω†Êà≥ÔºÅ(ÂèâËÖ∞)
  ÂÆâÂÖ®Á≥ªÁªüÂçáÁ∫ß‰∏≠...ÂçáÁ∫ßÂ§±Ë¥•Âõ†‰∏∫Ë¢´rua‰π±‰∫ÜÔºÅ
COUNT_REPLIES_GROUP: |-
  Â∞èÂè∂‰ªäÂ§©Â∑≤ÁªèË¢´Êà≥‰∫Ü_num_Ê¨°Âï¶Ôºå‰ºëÊÅØ‰∏Ä‰∏ãÂ•Ω‰∏çÂ•ΩÔºÅ
  Â∞èÂè∂‰ªäÂ§©Â∑≤ÁªèË¢´Êà≥‰∫Ü_num_Ê¨°Âï¶ÔºåÊúâÂÆåÊ≤°ÂÆåÔºÅ
  Â∞èÂè∂‰ªäÂ§©Â∑≤ÁªèË¢´Êà≥‰∫Ü_num_Ê¨°Âï¶ÔºåË¶ÅÊà≥ÂùèÊéâ‰∫ÜÔºÅ
  Â∞èÂè∂‰ªäÂ§©Â∑≤ÁªèË¢´Êà≥‰∫Ü_num_Ê¨°Âï¶ÔºåÂà´Êà≥‰∫ÜÔºÅÔºÅÔºÅ
  Â∞èÂè∂‰ªäÂ§©Â∑≤ÁªèË¢´Êà≥‰∫Ü_num_Ê¨°Âï¶Ôºå‰∏çÂáÜÊà≥‰∫ÜÔºÅÔºÅÔºÅ
  Â∞èÂè∂‰ªäÂ§©Â∑≤ÁªèË¢´Êà≥‰∫Ü_num_Ê¨°Âï¶ÔºåÂÜçÊà≥Â∞±Âùè‰∫ÜÔºÅ
COUNT_REPLIES_USER: |-
  ‰Ω†‰ªäÂ§©Â∑≤ÁªèÊà≥‰∫ÜÂ∞èÂè∂_num_Ê¨°Âï¶ÔºåÊòØ‰∏çÊòØÂñúÊ¨¢ÊàëÂëÄÔºü
  ‰Ω†‰ªäÂ§©Â∑≤ÁªèÊà≥‰∫ÜÂ∞èÂè∂_num_Ê¨°Âï¶ÔºåÂÜçÂñúÊ¨¢‰πü‰∏çËá≥‰∫éËøô‰πàÂñúÊ¨¢ÂêßÔºÅ
  ‰Ω†‰ªäÂ§©ÊâçÊà≥‰∫ÜÂ∞èÂè∂_num_Ê¨°‚ô°ÁúüÁöÑÊòØÊùÇÈ±ºÂë¢~
  ‰Ω†‰ªäÂ§©ÊâçÊà≥‰∫ÜÂ∞èÂè∂_num_Ê¨°ÔºåÂ§ßÂèîÁúüÈÄäÂïä~
  Â§ßÂèî‰∏ç‰ºö‰ªäÂ§©ÊâçÊà≥Â∞èÂè∂_num_Ê¨°Â∞±Ë¶Å‰∏çË°å‰∫ÜÂêß‚ô°
  ‰Ω†‰ªäÂ§©ÊâçÊà≥‰∫ÜÂ∞èÂè∂_num_Ê¨°ÔºåÊòØ‰∏çÊòØ‰∏çÂñúÊ¨¢Â∞èÂè∂‰∫Ü/(„Ñío„Ñí)/~~
POKE_BACK_TEXT_REPLIES: |-
  ÂìºÔºåÊàëÂèØÊòØ‰ºöËøòÊâãÁöÑÂì¶‚Äî‚Äî
  ÂêÉÊàë‰∏ÄÊã≥ÂñµÔºÅ
  ‰Ω†ÂàöÂàöÊòØ‰∏çÊòØÊà≥Êàë‰∫ÜÔºå‰Ω†ÊòØÂùèËõãÔºÅÊàëË¶ÅÊà≥ÂõûÂéªÔºåÂìºÔºÅÔºÅÔºÅ
  ÊòØ‰∏çÊòØË¶ÅÊú¨ËêùËéâÊèç‰Ω†‰∏ÄÈ°øÊâçÂºÄÂøÉÂïäÔºÅÔºÅÔºÅ
